required parameters
Kampfkarren/selene pull request #186
Opened 2020-12-04 02:36 UTC by Nickuhhh

UDim.new
UDim2.fromScale
UDim2.fromOffset
doesn't require parameters to be set

2020-12-04 07:09 UTC, Kampfkarren commented on selene/src/roblox/base.toml
> +
I don't understand any of the BrickColor.new declarations at this point, this implies that there exists a valid...6 argument BrickColor.new usage.

2020-12-04 07:10 UTC, Kampfkarren commented on selene/src/roblox/base.toml
>  required = false
This declaration is wrong--it would error for `CFrame.new(0, 0, 0)` for example, and would also block `CFrame.new(Vector3.new(), Vector3.new())`.

2020-12-04 07:11 UTC, Kampfkarren commented on selene/src/roblox/base.toml
> +required = false
This also doesn't make sense.

These aren't alternate definitions, they're all additional arguments to the same function.

2020-12-04 07:11 UTC, Kampfkarren commented
A lot of what you have is just incorrect--these aren't *alternate* definitions, they're *additional* arguments.

2020-12-04 12:04 UTC, Nickuhhh commented
> A lot of what you have is just incorrect--these aren't _alternate_ definitions, they're _additional_ arguments.

Hm, not sure how to make alternate parameters, I was following what the others looks like

2020-12-04 20:02 UTC, Kampfkarren commented
You're not able to without union types, which do not exist yet.

2020-12-04 21:14 UTC, Nickuhhh commented
Have reverted the attempted unioning, it now only changes the required parameters.

2020-12-04 21:25 UTC, Kampfkarren requested changes
Put these in the CHANGELOG as well.

2020-12-04 21:25 UTC, Kampfkarren commented on selene/src/roblox/base.toml
> +required = false
It doesn't feel useful to me to use `UDim2.fromOffset()` for an empty UDim2 when we have UDim2 for that purpose.

```suggestion
required = "use UDim2.new() if you want an empty UDim2"
```

2020-12-04 21:25 UTC, Kampfkarren commented on selene/src/roblox/base.toml
> +required = false
Same here.

```suggestion
required = "use UDim2.new() if you want an empty UDim2"
```

2020-12-04 22:43 UTC, Kampfkarren commented on CHANGELOG.md
> +- Fixed several required parameters.
This isn't descriptive enough. Please read similar changelog entries to see what is expected.

2020-12-04 23:50 UTC, Kampfkarren requested changes

2020-12-04 23:50 UTC, Kampfkarren commented on CHANGELOG.md
> +- Fixed `UDim2.fromOffset` and `UDim2.fromScale` to now require using `UDim.new` if no parameters are specified.
Last bikeshed, this should go under "Changed", since it's not really a bug fix.

2020-12-06 03:03 UTC, Kampfkarren approved these changes

2020-12-06 03:03 UTC, merged