Improve missing std files error
Kampfkarren/selene pull request #283
Opened 2021-08-04 13:27 UTC by soutenu

Fixes #272

2021-08-06 06:35 UTC, Kampfkarren commented on selene/src/main.rs
> +                        eprintln!("  {}", path.display())
```suggestion
                        eprintln!("  {}", path.display());
```

2021-08-06 06:36 UTC, Kampfkarren requested changes
This is the wrong place to put this check.

This is only going to work:

1. If you have the roblox feature flag enabled
2. If you have roblox in your std

This should be expanded past this.

2021-08-07 09:46 UTC, Kampfkarren requested changes
One last nitpick in the review.

I am a bit iffy about throwing away the `Err`, but then I noticed we just always assumed it was because the file wasn't found anyway, so I don't think this is introducing any bugs that didn't already exist, so no worries.

2021-08-07 09:46 UTC, Kampfkarren commented on selene/src/main.rs
> +                let roblox_std = Path::new("roblox.toml");
Do you need this variable? Just do `Path::new("roblox.toml").exists()`.

2021-08-21 18:23 UTC, Kampfkarren commented
Oh shoot, I completely forgot about this PR.

Can you make a changelog, then should be good to go?

2021-09-02 09:26 UTC, soutenu commented
Closing this to prevent dirtying the commit history.

2021-09-02 09:26 UTC, closed without merging

2021-09-02 13:14 UTC, Kampfkarren commented
Not sure what you mean by that, I squash commit everything--I've just been busy.