Add debug.setmemorycategory
Kampfkarren/selene pull request #354
Opened 2022-04-19 09:34 UTC by ffrostflame

I am not sure if I did this right. It's my first time

2022-04-19 19:58 UTC, Kampfkarren requested changes

2022-04-24 03:46 UTC, ffrostflame commented on CHANGELOG.md
> +- Added `debug.setmemorycategory` and `debug.setmemorycategory`
alright

2022-04-25 18:26 UTC, Kampfkarren commented
It doesn't look like you did either of my changes?

2022-04-26 19:31 UTC, Kampfkarren commented
You have now broken the original 0.18.0 changelog :P

2022-04-27 07:14 UTC, Kampfkarren commented
I misspoke, but both of your commits are still wrong.

There is NO 0.18.0 changelog, remove it.

2022-04-27 23:04 UTC, Kampfkarren commented on CHANGELOG.md
> +## Added
```suggestion
### Added
```

2022-04-27 23:04 UTC, Kampfkarren commented
Should be good now, will merge when CI passes.

2022-04-28 03:13 UTC, merged