Added Pre-Commit hook support
Kampfkarren/selene pull request #541
Opened 2023-07-24 17:26 UTC by Jarmos-san

Fixes #539 

This PR adds the pre-commit hooks configurations and documentation changes to reflect its support.

2023-07-29 22:14 UTC, f1rstlady commented on .pre-commit-hook.yaml
You forgot the `s` in the filename: `.pre-commit-hooks.yaml`.

2023-07-30 06:49 UTC, Jarmos-san commented on .pre-commit-hook.yaml
Ah thanks for the heads up! Fixed it in a quick commit.

2023-07-30 07:37 UTC, f1rstlady commented
Nice work! I had this on my todo list for half a year, decided yesterday to address it and found that you just implemented this last week. What a coincindence!

2023-07-30 07:42 UTC, f1rstlady requested changes

2023-07-30 07:42 UTC, f1rstlady commented on .pre-commit-hooks.yaml
Trying to run this hook via `pre-commit try-repo https://github.com/Jarmos-san/selene selene` fails with
```
===============================================================================
Using config:
===============================================================================
repos:
-   repo: https://github.com/Jarmos-san/selene
    rev: bd8b81cd7ee57727e4bd128a80bbdb1acc83a17f
    hooks:
    -   id: selene
===============================================================================
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /tmp/tmpcir77ixa/patch1690702419-3175.
[INFO] Initializing environment for https://github.com/Jarmos-san/selene.
[INFO] Installing environment for https://github.com/Jarmos-san/selene.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from /tmp/tmpcir77ixa/patch1690702419-3175.
An unexpected error has occurred: CalledProcessError: command: ('/tmp/tmpcir77ixa/repovkkeuvf0/rustenv-default/bin/cargo', 'install', '--bins', '--root', '/tmp/tmpcir77ixa/repovkkeuvf0/rustenv-default', '--path', '.')
return code: 101
stdout: (none)
stderr:
    info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
    info: latest update on 2023-07-13, rust version 1.71.0 (8ede3aae2 2023-07-12)
    info: downloading component 'cargo'
    info: downloading component 'clippy'
    info: downloading component 'rust-docs'
    info: downloading component 'rust-std'
    info: downloading component 'rustc'
    info: downloading component 'rustfmt'
    info: installing component 'cargo'
    info: installing component 'clippy'
    info: installing component 'rust-docs'
    info: installing component 'rust-std'
    info: installing component 'rustc'
    info: installing component 'rustfmt'
    error: found a virtual manifest at `/tmp/tmpcir77ixa/repovkkeuvf0/Cargo.toml` instead of a package manifest
Check the log at /home/bmr/.cache/pre-commit/pre-commit.log
```
I suspect Cargo expects something different?

2023-07-30 08:52 UTC, Jarmos-san commented on .pre-commit-hooks.yaml
Hey thanks for reporting the issue! I did some research and stumbled across https://github.com/rust-lang/cargo/issues/7599 which is why Cargo fails to correctly identify which `Cargo.toml` to use based on the correct workspace! I think it might be possible to circumvent this issue by specifying the exact path to the correct workspace using the `args` option of the `.pre-commit-hooks.yaml` file ([see related docs](https://pre-commit.com/index.html#hooks-args)).

Besides, I also noticed the other Docker based hook is breaking too! See the error logs I stumbled across:

```text
===============================================================================
Using config:
===============================================================================
repos:
-   repo: https://github.com/Jarmos-san/selene
    rev: bd8b81cd7ee57727e4bd128a80bbdb1acc83a17f
    hooks:
    -   id: selene-docker
===============================================================================
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /tmp/tmp5m_0u5m4/patch1690706713-30953.
[INFO] Initializing environment for https://github.com/Jarmos-san/selene.
[INFO] Installing environment for https://github.com/Jarmos-san/selene.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Restored changes from /tmp/tmp5m_0u5m4/patch1690706713-30953.
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/docker', 'build', '--tag', 'pre-commit-75061517ae24f03e43af03f990801e33', '--label', 'PRE_COMMIT', '--pull', '.')
return code: 1
stdout: (none)
stderr:
    #0 building with "default" instance using docker driver

    #1 [internal] load .dockerignore
    #1 transferring context: 2B done
    #1 DONE 0.8s

    #2 [internal] load build definition from Dockerfile
    #2 transferring dockerfile: 1.24kB 0.1s done
    #2 DONE 0.8s

    #3 [internal] load metadata for docker.io/library/rust:1.64-alpine3.14
    #3 ERROR: docker.io/library/rust:1.64-alpine3.14: not found

    #4 [internal] load metadata for docker.io/library/bash:latest
    #4 CANCELED
    ------
     > [internal] load metadata for docker.io/library/rust:1.64-alpine3.14:
    ------
    Dockerfile:17
    --------------------
      15 |         cargo install --branch main --git https://github.com/Kampfkarren/selene selene
      16 |
      17 | >>> FROM rust:1.64-alpine3.14 AS selene-light-musl-builder
      18 |     RUN apk add g++ && \
      19 |         cargo install --no-default-features --branch main --git https://github.com/Kampfkarren/selene selene
    --------------------
    ERROR: failed to solve: rust:1.64-alpine3.14: docker.io/library/rust:1.64-alpine3.14: not found
Check the log at /home/space/.cache/pre-commit/pre-commit.log
```
Is it because perhaps the `rust:1.64-alpine3.14` Image does not exists?

2023-07-30 09:39 UTC, f1rstlady commented on .pre-commit-hooks.yaml
I agree, the Docker build should be fixed in a separate PR.

Regarding the Cargo error, I'm also not familiar with Cargo. Maybe @Kampfkarren has an idea? pre-commit's installation procedure is documented [here](https://pre-commit.com/#rust).

2023-07-30 10:55 UTC, Jarmos-san commented on .pre-commit-hooks.yaml
Would you like to take the initiative to fix the `Dockerfile` since you already had the idea work on this PR earlier?

2023-07-30 11:01 UTC, f1rstlady commented on .pre-commit-hooks.yaml
I'm not familiar with containers...

2023-07-30 17:22 UTC, Jarmos-san commented on .pre-commit-hooks.yaml
Oh haha...cheers then! Don't worry I'll send another with a fix next weekend then. By then I hope Kamp will help us out figure out how to fix the `cargo` error.

2023-08-27 07:00 UTC, Kampfkarren commented
Apologies for the delay, been very busy.

@f1rstlady @Jarmos-san Yes the Docker build is broken...it was submitted by someone else and has not been properly maintained.

2023-08-27 07:02 UTC, Kampfkarren commented on .pre-commit-hooks.yaml
It looks like we can make it use `rust-alpine`, right? I always want latest Rust anyway.

2023-08-27 07:17 UTC, f1rstlady commented on .pre-commit-hooks.yaml
Yes, it works with `rust:alpine`; checked it recently.

2023-08-27 08:21 UTC, Jarmos-san commented on .pre-commit-hooks.yaml
Oh great glad `rust:alpine` works, so @f1rstlady do you want to try sharing a PR with a fixed `Dockerfile`? I can mark this PR a draft till you have shared a mergeable PR. What do you say?

Or if you want I can look into the current `Dockerfile` and see if I can fix the broken build.

2023-08-27 08:48 UTC, f1rstlady commented on .pre-commit-hooks.yaml
Here it is: #549

I haven't tested the corresponding pre-commit hook yet since I used podman instead of docker to buid the repaired image.

2023-10-29 05:40 UTC, amitds1997 commented
Any progress on this? If this needs some work, I can try to get it done

2023-10-29 08:24 UTC, Jarmos-san commented
Well I wanted to work on it but couldn't find time but please feel free to take it up. I would be equally pleased to have someone implement the Pre-Commit hook other than me.

2023-10-30 05:36 UTC, amitds1997 commented on .pre-commit-hooks.yaml
> +  entry: selene
```suggestion
  entry: /selene
```

This should fix the Docker run.

2023-10-30 05:42 UTC, amitds1997 commented
I looked into the `rust` language-based pre-commit hook. It calls `cargo install --bins --path .` and since we are using workspaces, it errors with `error: found a virtual manifest at <repo-path>/Cargo.toml instead of a package manifest`. I found a related issue: https://github.com/pre-commit/pre-commit/issues/2931, but the author seems to have opposed the idea of allowing the `--path` variable to have an input. So, we have to include a workaround in our build process somehow (not sure though, or if there is a workaround). Or, we can go ahead with just the system and the docker hook, for now. They should work.

Any recommendations: @Jarmos-san @Kampfkarren @f1rstlady?

@Jarmos-san If you could provide with me access, I would like to keep this PR open, just to build a continuity for the discussion. Or, I can open a fresh PR? Let me know what would be suitable for you.

2023-10-30 05:52 UTC, Jarmos-san commented
@amitds1997 you can reopen a new PR and I will not have no issues with it as long as I can run `selene` as a `pre-commit` hook. :sweat_smile: Just reference this PR so that I can close it accordingly and use it as a source of reference when I've to reconfigure my existing `pre-commit` hooks with `selene`.

2023-10-30 09:09 UTC, f1rstlady commented
@Jarmos-san may you merge the main to get the updated docker image?

2023-10-30 09:23 UTC, Jarmos-san commented
@f1rstlady do you want me to update this PR's branch with the latest updates from the `main` branch? I think @amitds1997 is going to fork and share his own PR so I think it will have the latest commits to the `main` branch any way. Once he does it, I can close this PR in favour of the other one.

2023-10-30 09:34 UTC, f1rstlady commented
Ok, now I get your idea!

2023-10-30 16:10 UTC, amitds1997 commented
Created https://github.com/Kampfkarren/selene/pull/565 for this.

2023-10-31 04:13 UTC, closed without merging