Remove version constraints on container images
Kampfkarren/selene pull request #549
Opened 2023-08-27 08:46 UTC by f1rstlady

This fixes errors during the build of this image, occuring due to non-existent version tags.

2023-08-27 08:52 UTC, Jarmos-san requested changes
Can you make use [build-time variables](https://docs.docker.com/engine/reference/commandline/build/#build-arg) instead? That would allow for more flexibility to build the Docker Image. See #550 for some ideas I had in mind.

2023-08-27 09:38 UTC, f1rstlady commented
> Can you make use [build-time variables](https://docs.docker.com/engine/reference/commandline/build/#build-arg) instead? That would allow for a more flexible to build the Docker Image. See #550 for some ideas I had in mind.

Do we need this flexibility? I'm asking because I prefer to add the minimal needed abstraction only. In addition, I suggest to distinguish between _fixing_ and _enhancing_ the image.

Other ideas for enhancements:

1. Do we need the debian-based builds? Afaik, docker is used only by the pre-commit hook, which in turn uses the alpine-based image only.
2. @Kampfkarren [As the build pipeline shows](https://github.com/Kampfkarren/selene/blob/b9c27b0d4de9c7cb84b111ed58f825143bb104a0/.github/workflows/build.yml#L198), the built images are pushed to the Docker hub. But under which account? Shall we document the location of the builds?

2023-08-27 09:54 UTC, Jarmos-san commented
> Do we need this flexibility? I'm asking because I prefer to add the minimal needed abstraction only. In addition, I suggest to distinguish between fixing and enhancing the image.

Don't fix what's not broken is definitely the easier way around the issue with the Docker build issue right now tbh. The flexible enhancements I suggested on the other hand is to future-proof a potential scenario wherein someone had to test the build against a different Rust Docker Image for whatever reason.

For example, what if someone had to quickly check if a certain feature works on a particular Image or perhaps a specific version of Rust? Passing the build-time variables to `docker` would allow us to do that.

The other intention I had in mind was, since the current `Dockerfile` is worked on, why not do it the proper way right now instead of waiting for someone else to do it in the future? It'll allow Kamp to be relieved off of some maintenance burden as well.

2023-08-27 10:15 UTC, Jarmos-san approved these changes

2023-09-12 04:51 UTC, Kampfkarren commented
@f1rstlady My assumption for the account is going to be `boyned`. This looks fine

2023-09-29 04:21 UTC, merged